/-
  Surd.Galois.Permutation — Permutation groups on finite sets with
  Schreier–Sims machinery.

  Permutations on {0, 1, ..., n-1} stored as image arrays.
  Schreier–Sims computes a base and strong generating set (BSGS).
-/
namespace Surd

-- ---------------------------------------------------------------------------
-- Permutations
-- ---------------------------------------------------------------------------

/-- A permutation σ ∈ Sₙ acting on {0, 1, ..., n-1}.
    Stored as the image array [σ(0), σ(1), ..., σ(n-1)]. -/
structure Perm where
  permN : Nat
  permImg : Array Nat
  deriving Inhabited, Repr, BEq

/-- Apply σ to a point: σ(i). -/
def permApply (p : Perm) (i : Nat) : Nat :=
  p.permImg.getD i i

/-- Compose two permutations (right-to-left): (σ · τ)(i) = σ(τ(i)). -/
def permCompose (sigma tau : Perm) : Perm :=
  let n := sigma.permN
  let img := (List.range n).toArray.map fun i =>
    permApply sigma (permApply tau i)
  ⟨n, img⟩

/-- The inverse permutation σ⁻¹. -/
def permInverse (p : Perm) : Perm :=
  let n := p.permN
  let inv := (List.range n).foldl (fun arr i =>
    let img := permApply p i
    arr.set! img i
  ) ((List.range n).toArray)
  ⟨n, inv⟩

/-- The identity permutation on {0, ..., n-1}. -/
def permId (n : Nat) : Perm :=
  ⟨n, (List.range n).toArray⟩

/-- Test whether a permutation is the identity. -/
def permIsId (p : Perm) : Bool :=
  (List.range p.permN).all fun i => permApply p i == i

/-- Cycle decomposition of σ, excluding fixed points. -/
partial def permCycles (p : Perm) : List (List Nat) :=
  go [] 0
where
  go (visited : List Nat) (i : Nat) : List (List Nat) :=
    if i ≥ p.permN then []
    else if visited.contains i then go visited (i + 1)
    else if permApply p i == i then go (i :: visited) (i + 1)
    else
      let cyc := traceCycle i i [i]
      let visited' := cyc ++ visited
      cyc :: go visited' (i + 1)
  traceCycle (start cur : Nat) (acc : List Nat) : List Nat :=
    let next := permApply p cur
    if next == start then acc
    else traceCycle start next (acc ++ [next])

/-- The order of a permutation (LCM of cycle lengths). -/
def permOrder (p : Perm) : Nat :=
  if permIsId p then 1
  else (permCycles p).foldl (fun acc c => Nat.lcm acc c.length) 1

/-- Sign of a permutation: 1 for even, -1 for odd. -/
def permSign (p : Perm) : Int :=
  let k := (permCycles p).foldl (fun acc c => acc + c.length - 1) 0
  if k % 2 == 0 then 1 else -1

/-- Build a permutation from cycle notation.
    fromCycles 5 [[0,1,2],[3,4]] → (0 1 2)(3 4) ∈ S₅. -/
def fromCycles (n : Nat) (cycles : List (List Nat)) : Perm :=
  let base := (List.range n).toArray
  let final := cycles.foldl (fun arr cyc =>
    match cyc with
    | [] => arr
    | c0 :: _ =>
      let pairs := cyc.zip (cyc.drop 1 ++ [c0])
      pairs.foldl (fun arr' (a, b) => arr'.set! a b) arr
  ) base
  ⟨n, final⟩

/-- Build a permutation from a full image list. -/
def fromMapping (img : List Nat) : Perm :=
  ⟨img.length, img.toArray⟩

/-- The orbit of a point under a group generated by the given permutations. -/
partial def orbit (pt : Nat) (gens : List Perm) : List Nat :=
  bfs [pt] [pt]
where
  bfs (visited queue : List Nat) : List Nat :=
    match queue with
    | [] => visited
    | x :: rest =>
      let newPts := gens.filterMap fun g =>
        let y := permApply g x
        if visited.contains y then none else some y
      bfs (visited ++ newPts) (rest ++ newPts)

-- ---------------------------------------------------------------------------
-- Schreier–Sims
-- ---------------------------------------------------------------------------

/-- A base and strong generating set (BSGS) for a permutation group G ≤ Sₙ. -/
structure BSGS where
  bsgsBase : List Nat
  bsgsTransversals : List (List (Nat × Perm))  -- association lists
  bsgsN : Nat
  deriving Inhabited

/-- Look up a key in a transversal. -/
private def transLookup (trans : List (Nat × Perm)) (key : Nat) : Option Perm :=
  match trans.find? (fun p => p.1 == key) with
  | some (_, p) => some p
  | none => none

/-- Sift g through a BSGS, returning the residue. -/
private partial def sift (base : List Nat) (trans : List (List (Nat × Perm)))
    (g : Perm) : Perm :=
  go 0 g
where
  go (i : Nat) (h : Perm) : Perm :=
    if i ≥ base.length then h
    else
      let img := permApply h (base.get! i)
      match transLookup (trans.get! i) img with
      | none => h
      | some u => go (i + 1) (permCompose (permInverse u) h)

/-- BFS from base point to build orbit + coset reps. -/
private partial def buildTransversal (n : Nat) (pt : Nat) (gs : List Perm) : List (Nat × Perm) :=
  bfs [(pt, permId n)] [pt]
where
  bfs (visited : List (Nat × Perm)) (queue : List Nat) : List (Nat × Perm) :=
    match queue with
    | [] => visited
    | x :: rest =>
      let ux := match visited.find? (fun p => p.1 == x) with
        | some (_, u) => u | none => permId n
      let candidates := gs.map fun g => (permApply g x, permCompose g ux)
      let newOnes := candidates.filter fun (y, _) => !visited.any (fun p => p.1 == y)
      bfs (visited ++ newOnes) (rest ++ newOnes.map (·.1))

/-- Extend a BSGS with a non-identity residue. -/
private def extendBSGS (n : Nat) (bsgs : BSGS) (g : Perm) : BSGS :=
  let base := bsgs.bsgsBase
  let trans := bsgs.bsgsTransversals
  let fixedLevels := (base.takeWhile (fun b => permApply g b == b)).length
  if fixedLevels ≥ base.length then
    let pt := match (List.range n).find? (fun i => permApply g i != i) with
      | some p => p
      | none => 0
    ⟨base ++ [pt], trans ++ [buildTransversal n pt [g]], n⟩
  else
    let existingReps := (trans.get! fixedLevels).map (·.2)
    let newTrans := buildTransversal n (base.get! fixedLevels) (g :: existingReps)
    ⟨base, trans.take fixedLevels ++ [newTrans] ++ trans.drop (fixedLevels + 1), n⟩

/-- Compute BSGS via incremental Schreier–Sims. -/
partial def schreierSims (n : Nat) (gens : List Perm) : BSGS :=
  if gens.isEmpty || gens.all permIsId then ⟨[], [], n⟩
  else
    let initial := gens.foldl (fun bsgs g =>
      let r := sift bsgs.bsgsBase bsgs.bsgsTransversals g
      if permIsId r then bsgs else extendBSGS n bsgs r
    ) (BSGS.mk [] [] n)
    saturate initial
where
  siftInsert (bsgs : BSGS) (g : Perm) : BSGS :=
    let r := sift bsgs.bsgsBase bsgs.bsgsTransversals g
    if permIsId r then bsgs else extendBSGS n bsgs r

  schreierGens (bsgs : BSGS) : List Perm :=
    let base := bsgs.bsgsBase
    let trans := bsgs.bsgsTransversals
    (List.range trans.length).flatMap fun i =>
      let b := base.get! i
      let transversal := trans.get! i
      transversal.flatMap fun (_, u) =>
        let beta := permApply u b
        gens.filterMap fun s =>
          let sBeta := permApply s beta
          let uSBeta := match transLookup transversal sBeta with
            | some p => p | none => permId n
          let sg := permCompose (permInverse uSBeta) (permCompose s u)
          if permIsId sg then none else some sg

  saturate (bsgs : BSGS) : BSGS :=
    let sGens := schreierGens bsgs
    let bsgs' := sGens.foldl siftInsert bsgs
    let same := bsgs'.bsgsTransversals.length == bsgs.bsgsTransversals.length &&
       (List.range bsgs.bsgsTransversals.length).all (fun i =>
         (bsgs.bsgsTransversals.get! i).length == (bsgs'.bsgsTransversals.get! i).length)
    if same then bsgs' else saturate bsgs'

/-- The order of the group: |G| = ∏ |Δᵢ|. -/
def groupOrder (bsgs : BSGS) : Nat :=
  bsgs.bsgsTransversals.foldl (fun acc t => acc * t.length) 1

/-- Test whether a permutation belongs to the group (sifting). -/
partial def groupContains (bsgs : BSGS) (g : Perm) : Bool :=
  let r := sift bsgs.bsgsBase bsgs.bsgsTransversals g
  permIsId r

/-- Enumerate all elements of the group. -/
def groupElements (bsgs : BSGS) : List Perm :=
  match bsgs.bsgsTransversals with
  | [] => [permId bsgs.bsgsN]
  | _ =>
    let reps := bsgs.bsgsTransversals.map (·.map (·.2))
    allCombos reps |>.map fun combo =>
      combo.foldl permCompose (permId bsgs.bsgsN)
where
  allCombos : List (List Perm) → List (List Perm)
    | [] => [[]]
    | xs :: rest =>
      let tails := allCombos rest
      xs.flatMap fun x => tails.map fun t => x :: t

end Surd
