%---------------------------------------------------------------------------%
% vim: ft=mercury ts=4 sw=4 et
%---------------------------------------------------------------------------%
% File: groebner.m
% Main author: nyc
%
% Gröbner basis computation for multivariate polynomial ideals.
%
% Implements Buchberger's algorithm with:
%   - Buchberger's first criterion (coprime leading monomials -> skip)
%   - Inter-reduction of the final basis
%   - Incremental extension (extendBasis)
%
%---------------------------------------------------------------------------%

:- module groebner.
:- interface.

:- import_module list.
:- import_module multivariate.
:- import_module poly.
:- import_module set.

%---------------------------------------------------------------------------%
% Monomial orderings
%---------------------------------------------------------------------------%

    % A total order on monomials.
    %
:- type mono_ord == (func(mono, mono) = comparison_result).

    % Graded reverse lexicographic order.
    %
:- func grevlex_ord = mono_ord.

    % Graded lexicographic order.
    %
:- func grlex_ord = mono_ord.

    % Pure lexicographic order.
    %
:- func lex_ord = mono_ord.

    % Elimination order: variables in the set are more expensive.
    %
:- func elim_ord(set(var)) = mono_ord.

%---------------------------------------------------------------------------%
% Gröbner basis
%---------------------------------------------------------------------------%

    % A Gröbner basis together with its monomial ordering.
    %
:- type gb(K)
    --->    gb(
                gb_ord   :: mono_ord,
                gb_polys :: list(mpoly(K))
            ).

    % Compute a Gröbner basis for the ideal generated by the given polynomials.
    %
:- func groebner_basis(mono_ord, list(mpoly(K))) = gb(K) <= field(K).

    % Extend an existing Gröbner basis with new generators.
    %
:- func extend_basis(list(mpoly(K)), gb(K)) = gb(K) <= field(K).

%---------------------------------------------------------------------------%
% Reduction
%---------------------------------------------------------------------------%

    % Reduce a polynomial modulo the Gröbner basis.
    %
:- func gb_reduce(gb(K), mpoly(K)) = mpoly(K) <= field(K).

    % Reduce completely, making the result monic if nonzero.
    %
:- func gb_reduce_completely(gb(K), mpoly(K)) = mpoly(K) <= field(K).

%---------------------------------------------------------------------------%
% Multivariate polynomial division
%---------------------------------------------------------------------------%

    % Divide a polynomial by a list of divisors under the given ordering.
    % Returns {quotients, remainder}.
    %
:- func div_mod_mpoly(mono_ord, mpoly(K), list(mpoly(K)))
    = {list(mpoly(K)), mpoly(K)} <= field(K).

%---------------------------------------------------------------------------%
%---------------------------------------------------------------------------%

:- implementation.

:- use_module int.
:- import_module map.
:- import_module require.

%---------------------------------------------------------------------------%
% Monomial orderings
%---------------------------------------------------------------------------%

grevlex_ord = ( func(A, B) = compare_grevlex(A, B) ).

grlex_ord = ( func(A, B) = R :-
    DA = mono_degree(A),
    DB = mono_degree(B),
    ( if DA = DB then
        R = compare_grlex_tiebreak(A, B)
    else if int.'<'(DA, DB) then
        R = (<)
    else
        R = (>)
    )
).

:- func compare_grlex_tiebreak(mono, mono) = comparison_result.

compare_grlex_tiebreak(mono(A), mono(B)) = Result :-
    builtin.compare(Result, A, B).

lex_ord = ( func(A, B) = compare_lex(A, B) ).

:- func compare_lex(mono, mono) = comparison_result.

compare_lex(mono(A), mono(B)) = Result :-
    map.union(merge_keep_left_v, A, B, AllVars),
    map.keys(AllVars, VarList),
    list.reverse(VarList, RevVars),
    compare_lex_vars(RevVars, A, B, Result).

:- pred merge_keep_left_v(int::in, int::in, int::out) is det.

merge_keep_left_v(L, _, L).

:- pred compare_lex_vars(list(var)::in, map(var, int)::in,
    map(var, int)::in, comparison_result::out) is det.

compare_lex_vars([], _, _, (=)).
compare_lex_vars([V | Vs], A, B, Result) :-
    EA = ( if map.search(A, V, EA0) then EA0 else 0 ),
    EB = ( if map.search(B, V, EB0) then EB0 else 0 ),
    ( if EA = EB then
        compare_lex_vars(Vs, A, B, Result)
    else
        compare(Result, EA, EB)
    ).

elim_ord(Elims) = ( func(A, B) = R :-
    split_mono(Elims, A, AE, AR),
    split_mono(Elims, B, BE, BR),
    CmpE = compare_grevlex(AE, BE),
    ( if CmpE = (=) then
        R = compare_grevlex(AR, BR)
    else
        R = CmpE
    )
).

:- pred split_mono(set(var)::in, mono::in, mono::out, mono::out) is det.

split_mono(Vs, mono(M), mono(InSet), mono(OutSet)) :-
    map.foldl2(( pred(V::in, E::in, In0::in, In1::out,
            Out0::in, Out1::out) is det :-
        ( if set.member(V, Vs) then
            map.det_insert(V, E, In0, In1),
            Out1 = Out0
        else
            In1 = In0,
            map.det_insert(V, E, Out0, Out1)
        )
    ), M, map.init, InSet, map.init, OutSet).

%---------------------------------------------------------------------------%
% Leading term extraction
%---------------------------------------------------------------------------%

:- pred lead_term(mono_ord::in, mpoly(K)::in, mono::out, K::out) is semidet.

lead_term(Cmp, mpoly(M), BestMono, BestCoeff) :-
    map.keys(M, [FirstKey | _]),
    map.lookup(M, FirstKey, FirstVal),
    map.foldl2(( pred(Mono::in, Coeff::in, BM0::in, BM1::out,
            BC0::in, BC1::out) is det :-
        CmpResult = Cmp(Mono, BM0),
        ( if CmpResult = (>) then
            BM1 = Mono,
            BC1 = Coeff
        else
            BM1 = BM0,
            BC1 = BC0
        )
    ), M, FirstKey, BestMono, FirstVal, BestCoeff).

:- pred lead_mono(mono_ord::in, mpoly(K)::in, mono::out) is semidet.

lead_mono(Cmp, P, Mono) :-
    lead_term(Cmp, P, Mono, _).

:- pred lead_coeff_m(mono_ord::in, mpoly(K)::in, K::out) is semidet.

lead_coeff_m(Cmp, P, Coeff) :-
    lead_term(Cmp, P, _, Coeff).

%---------------------------------------------------------------------------%
% Multivariate polynomial division
%---------------------------------------------------------------------------%

:- type divisor_info(K)
    --->    divisor_info(
                div_index :: int,
                div_mono  :: mono,
                div_coeff :: K
            ).

div_mod_mpoly(Cmp, F, Divisors) = {Qs, R} :-
    N = list.length(Divisors),
    list.duplicate(N, mp_zero, QsInit),
    build_divisor_infos(Cmp, Divisors, 0, DIs),
    div_mod_loop(Cmp, F, Divisors, DIs, QsInit, Qs, mp_zero, R).

:- pred build_divisor_infos(mono_ord::in, list(mpoly(K))::in, int::in,
    list(divisor_info(K))::out) is det <= field(K).

build_divisor_infos(_, [], _, []).
build_divisor_infos(Cmp, [G | Gs], I, DIs) :-
    ( if lead_term(Cmp, G, LM, LC) then
        build_divisor_infos(Cmp, Gs, int.'+'(I, 1), RestDIs),
        DIs = [divisor_info(I, LM, LC) | RestDIs]
    else
        build_divisor_infos(Cmp, Gs, int.'+'(I, 1), DIs)
    ).

:- pred div_mod_loop(mono_ord::in, mpoly(K)::in, list(mpoly(K))::in,
    list(divisor_info(K))::in,
    list(mpoly(K))::in, list(mpoly(K))::out,
    mpoly(K)::in, mpoly(K)::out) is det <= field(K).

div_mod_loop(Cmp, P, Divisors, DIs, Qs0, Qs, R0, R) :-
    ( if mp_is_zero(P) then
        Qs = Qs0,
        R = R0
    else if lead_term(Cmp, P, PM, PC) then
        ( if find_divisor(PM, DIs, DI) then
            QM = mono_div(PM, div_mono(DI)),
            QC = field_div(PC, div_coeff(DI)),
            QI = mpoly(map.singleton(QM, QC)),
            Idx = div_index(DI),
            list.det_index0(Divisors, Idx, Div),
            P1 = mp_sub(P, mp_mul(QI, Div)),
            update_at(Idx, QI, Qs0, Qs1),
            div_mod_loop(Cmp, P1, Divisors, DIs, Qs1, Qs, R0, R)
        else
            LT = mpoly(map.singleton(PM, PC)),
            P1 = mp_sub(P, LT),
            R1 = mp_add(R0, LT),
            div_mod_loop(Cmp, P1, Divisors, DIs, Qs0, Qs, R1, R)
        )
    else
        Qs = Qs0,
        R = R0
    ).

:- pred find_divisor(mono::in, list(divisor_info(K))::in,
    divisor_info(K)::out) is semidet.

find_divisor(PM, [DI | DIs], Result) :-
    ( if mono_divides(div_mono(DI), PM) then
        Result = DI
    else
        find_divisor(PM, DIs, Result)
    ).

:- pred update_at(int::in, mpoly(K)::in,
    list(mpoly(K))::in, list(mpoly(K))::out) is det <= ring(K).

update_at(_, _, [], []).
update_at(I, QI, [Q | Qs], [Q1 | Qs1]) :-
    ( if I = 0 then
        Q1 = mp_add(Q, QI),
        Qs1 = Qs
    else
        Q1 = Q,
        update_at(int.'-'(I, 1), QI, Qs, Qs1)
    ).

%---------------------------------------------------------------------------%
% Reduction
%---------------------------------------------------------------------------%

:- type red_info(K)
    --->    red_info(
                red_mono  :: mono,
                red_coeff :: K,
                red_poly  :: mpoly(K)
            ).

:- func reduce_poly(mono_ord, mpoly(K), list(mpoly(K))) = mpoly(K)
    <= field(K).

reduce_poly(Cmp, F, Divisors) = Result :-
    build_red_infos(Cmp, Divisors, RIs),
    reduce_loop(Cmp, F, RIs, mp_zero, Result).

:- pred build_red_infos(mono_ord::in, list(mpoly(K))::in,
    list(red_info(K))::out) is det <= field(K).

build_red_infos(_, [], []).
build_red_infos(Cmp, [G | Gs], RIs) :-
    ( if lead_term(Cmp, G, LM, LC) then
        build_red_infos(Cmp, Gs, RestRIs),
        RIs = [red_info(LM, LC, G) | RestRIs]
    else
        build_red_infos(Cmp, Gs, RIs)
    ).

:- pred reduce_loop(mono_ord::in, mpoly(K)::in,
    list(red_info(K))::in,
    mpoly(K)::in, mpoly(K)::out) is det <= field(K).

reduce_loop(Cmp, P, RIs, R0, R) :-
    ( if mp_is_zero(P) then
        R = R0
    else if lead_term(Cmp, P, PM, PC) then
        ( if find_red(PM, RIs, RI) then
            QM = mono_div(PM, red_mono(RI)),
            QC = field_div(PC, red_coeff(RI)),
            QT = mpoly(map.singleton(QM, QC)),
            P1 = mp_sub(P, mp_mul(QT, red_poly(RI))),
            reduce_loop(Cmp, P1, RIs, R0, R)
        else
            LT = mpoly(map.singleton(PM, PC)),
            P1 = mp_sub(P, LT),
            R1 = mp_add(R0, LT),
            reduce_loop(Cmp, P1, RIs, R1, R)
        )
    else
        R = R0
    ).

:- pred find_red(mono::in, list(red_info(K))::in,
    red_info(K)::out) is semidet.

find_red(PM, [RI | RIs], Result) :-
    ( if mono_divides(red_mono(RI), PM) then
        Result = RI
    else
        find_red(PM, RIs, Result)
    ).

%---------------------------------------------------------------------------%
% S-polynomials
%---------------------------------------------------------------------------%

:- func s_polynomial(mono_ord, mpoly(K), mpoly(K)) = mpoly(K) <= field(K).

s_polynomial(Cmp, F, G) = Result :-
    ( if lead_term(Cmp, F, MF, CF), lead_term(Cmp, G, MG, CG) then
        L = mono_lcm(MF, MG),
        QF = mono_div(L, MF),
        QG = mono_div(L, MG),
        TF = mp_scale(field_div(ring_one, CF), mul_by_mono(QF, F)),
        TG = mp_scale(field_div(ring_one, CG), mul_by_mono(QG, G)),
        Result = mp_sub(TF, TG)
    else
        Result = mp_zero
    ).

%---------------------------------------------------------------------------%
% Buchberger's algorithm
%---------------------------------------------------------------------------%

groebner_basis(Cmp, Gens) = gb(Cmp, Reduced) :-
    NonZero = list.filter(( pred(G::in) is semidet :-
        not mp_is_zero(G)
    ), Gens),
    N = list.length(NonZero),
    all_pairs(0, N, Pairs),
    buchberger_with_pairs(Cmp, NonZero, Pairs, Basis),
    inter_reduce(Cmp, Basis, Reduced).

extend_basis(NewGens, gb(Cmp, Existing)) = gb(Cmp, Final) :-
    NonZero = list.filter(( pred(G::in) is semidet :-
        not mp_is_zero(G)
    ), NewGens),
    list.filter_map(( pred(G::in, R::out) is semidet :-
        R = reduce_poly(Cmp, G, Existing),
        not mp_is_zero(R)
    ), NonZero, Reduced),
    Combined = Existing ++ Reduced,
    NExisting = list.length(Existing),
    NCombined = list.length(Combined),
    cross_pairs(NExisting, NCombined, CrossPairs),
    buchberger_with_pairs(Cmp, Combined, CrossPairs, Basis),
    inter_reduce(Cmp, Basis, Final).

gb_reduce(gb(Cmp, Basis), F) = reduce_poly(Cmp, F, Basis).

gb_reduce_completely(GB, F) = Result :-
    R = gb_reduce(GB, F),
    ( if lead_coeff_m(gb_ord(GB), R, LC),
        not ring_is_zero(LC)
    then
        Result = mp_scale(field_div(ring_one, LC), R)
    else
        Result = R
    ).

:- pred all_pairs(int::in, int::in, list({int, int})::out) is det.

all_pairs(I, N, Pairs) :-
    ( if int.'>='(I, int.'-'(N, 1)) then
        Pairs = []
    else
        j_pairs(I, int.'+'(I, 1), N, IPairs),
        all_pairs(int.'+'(I, 1), N, RestPairs),
        Pairs = IPairs ++ RestPairs
    ).

:- pred j_pairs(int::in, int::in, int::in,
    list({int, int})::out) is det.

j_pairs(I, J, N, Pairs) :-
    ( if int.'>='(J, N) then
        Pairs = []
    else
        j_pairs(I, int.'+'(J, 1), N, RestPairs),
        Pairs = [{I, J} | RestPairs]
    ).

:- pred cross_pairs(int::in, int::in,
    list({int, int})::out) is det.

cross_pairs(NExisting, NCombined, Pairs) :-
    cross_pairs_loop(0, 0, NExisting, NCombined, Pairs).

:- pred cross_pairs_loop(int::in, int::in, int::in, int::in,
    list({int, int})::out) is det.

cross_pairs_loop(I, J, NExisting, N, Pairs) :-
    ( if int.'>='(I, int.'-'(N, 1)) then
        Pairs = []
    else if int.'>='(J, N) then
        cross_pairs_loop(int.'+'(I, 1), int.'+'(I, 2), NExisting, N, Pairs)
    else if int.'<'(J, int.'+'(I, 1)) then
        cross_pairs_loop(I, int.'+'(J, 1), NExisting, N, Pairs)
    else if int.'>='(I, NExisting) ; int.'>='(J, NExisting) then
        cross_pairs_loop(I, int.'+'(J, 1), NExisting, N, RestPairs),
        Pairs = [{I, J} | RestPairs]
    else
        cross_pairs_loop(I, int.'+'(J, 1), NExisting, N, Pairs)
    ).

:- pred buchberger_with_pairs(mono_ord::in, list(mpoly(K))::in,
    list({int, int})::in, list(mpoly(K))::out) is det <= field(K).

buchberger_with_pairs(Cmp, Basis0, Pairs0, Basis) :-
    ( if Pairs0 = [] then
        Basis = Basis0
    else if Pairs0 = [{I, J} | RestPairs] then
        N = list.length(Basis0),
        ( if int.'>='(I, N) ; int.'>='(J, N) then
            buchberger_with_pairs(Cmp, Basis0, RestPairs, Basis)
        else if
            list.det_index0(Basis0, I, FI),
            list.det_index0(Basis0, J, FJ),
            buchberger_criterion1(Cmp, FI, FJ)
        then
            buchberger_with_pairs(Cmp, Basis0, RestPairs, Basis)
        else
            list.det_index0(Basis0, I, FI2),
            list.det_index0(Basis0, J, FJ2),
            SP = s_polynomial(Cmp, FI2, FJ2),
            R = reduce_poly(Cmp, SP, Basis0),
            ( if mp_is_zero(R) then
                buchberger_with_pairs(Cmp, Basis0, RestPairs, Basis)
            else
                K = list.length(Basis0),
                new_pairs(K, NewPairs),
                Basis1 = Basis0 ++ [R],
                buchberger_with_pairs(Cmp, Basis1,
                    RestPairs ++ NewPairs, Basis)
            )
        )
    else
        unexpected($pred, "unreachable")
    ).

:- pred new_pairs(int::in, list({int, int})::out) is det.

new_pairs(K, Pairs) :-
    new_pairs_loop(0, K, Pairs).

:- pred new_pairs_loop(int::in, int::in, list({int, int})::out) is det.

new_pairs_loop(M, K, Pairs) :-
    ( if int.'>='(M, K) then
        Pairs = []
    else
        new_pairs_loop(int.'+'(M, 1), K, RestPairs),
        Pairs = [{K, M} | RestPairs]
    ).

:- pred buchberger_criterion1(mono_ord::in, mpoly(K)::in,
    mpoly(K)::in) is semidet.

buchberger_criterion1(Cmp, F, G) :-
    ( if lead_mono(Cmp, F, MF), lead_mono(Cmp, G, MG) then
        mono_gcd(MF, MG) = mono_one
    else
        true
    ).

:- pred inter_reduce(mono_ord::in, list(mpoly(K))::in,
    list(mpoly(K))::out) is det <= field(K).

inter_reduce(Cmp, Basis, Result) :-
    inter_reduce_loop(Cmp, [], Basis, Result).

:- pred inter_reduce_loop(mono_ord::in, list(mpoly(K))::in,
    list(mpoly(K))::in, list(mpoly(K))::out) is det <= field(K).

inter_reduce_loop(_, Done, [], Result) :-
    list.reverse(Done, Result).
inter_reduce_loop(Cmp, Done, [F | Fs], Result) :-
    Others = Done ++ Fs,
    F1 = reduce_poly(Cmp, F, Others),
    ( if mp_is_zero(F1) then
        inter_reduce_loop(Cmp, Done, Fs, Result)
    else
        ( if lead_coeff_m(Cmp, F1, LC), not ring_is_zero(LC) then
            F2 = mp_scale(field_div(ring_one, LC), F1)
        else
            F2 = F1
        ),
        inter_reduce_loop(Cmp, [F2 | Done], Fs, Result)
    ).

%---------------------------------------------------------------------------%
:- end_module groebner.
%---------------------------------------------------------------------------%
