package surd

/** Permutation on {0, 1, ..., n-1} stored as an image list. */
final case class Perm(images: Vector[Int]):
  def n: Int = images.length

  /** Apply permutation to a point. */
  def apply(i: Int): Int = images(i)

  /** Compose: (this compose that)(i) = this(that(i)). */
  def compose(that: Perm): Perm =
    require(n == that.n)
    Perm(that.images.map(images(_)))

  /** Inverse permutation. */
  def inverse: Perm =
    val inv = Array.ofDim[Int](n)
    for i <- 0 until n do inv(images(i)) = i
    Perm(inv.toVector)

  /** Check if this is the identity. */
  def isIdentity: Boolean = images.indices.forall(i => images(i) == i)

  /** Order of the permutation (smallest k > 0 with sigma^k = id). */
  def order: Int =
    val cycLens = cycles.map(_.length)
    if cycLens.isEmpty then 1
    else cycLens.foldLeft(1)(Perm.lcm)

  /** Cycle decomposition. Returns list of cycles (each of length >= 1). */
  def cycles: Vector[Vector[Int]] =
    val visited = Array.fill(n)(false)
    val result = Vector.newBuilder[Vector[Int]]
    for i <- 0 until n do
      if !visited(i) then
        val cycle = Vector.newBuilder[Int]
        var j = i
        while !visited(j) do
          visited(j) = true
          cycle += j
          j = images(j)
        val c = cycle.result()
        if c.length > 1 then result += c
    result.result()

  /** Sign of the permutation: +1 for even, -1 for odd. */
  def sign: Int =
    val transpositions = cycles.map(_.length - 1).sum
    if transpositions % 2 == 0 then 1 else -1

  override def toString: String =
    if isIdentity then "id"
    else cycles.map(c => "(" + c.mkString(" ") + ")").mkString

object Perm:
  /** Identity permutation on n elements. */
  def identity(n: Int): Perm = Perm((0 until n).toVector)

  /** Transposition (i j). */
  def transposition(n: Int, i: Int, j: Int): Perm =
    val img = (0 until n).toVector
    Perm(img.updated(i, j).updated(j, i))

  /** Cyclic permutation (i0 i1 ... ik). */
  def cycle(n: Int, elems: Int*): Perm =
    val img = (0 until n).toVector.toArray
    for k <- elems.indices do
      img(elems(k)) = elems((k + 1) % elems.length)
    Perm(img.toVector)

  /** All permutations of {0, ..., n-1}. */
  def allPerms(n: Int): Vector[Perm] =
    (0 until n).toVector.permutations.map(Perm(_)).toVector

  /** Order of the group generated by a set of permutations.
    * Uses orbit computation (simplified Schreier-Sims).
    */
  def groupOrder(gens: Vector[Perm]): Int =
    if gens.isEmpty then 1
    else
      val n = gens.head.n
      // Generate all elements by closure
      val elems = scala.collection.mutable.Set(Perm.identity(n))
      var frontier = gens.toSet
      while frontier.nonEmpty do
        val newElems = for
          a <- frontier
          b <- elems ++ frontier
          c <- Vector(a.compose(b), b.compose(a))
          if !elems.contains(c)
        yield c
        elems ++= frontier
        frontier = newElems
        if elems.size > 1000 then return elems.size // safety limit
      elems.size

  private def lcm(a: Int, b: Int): Int =
    if a == 0 || b == 0 then 0
    else (a / gcd(a, b)) * b

  private def gcd(a: Int, b: Int): Int =
    if b == 0 then a.abs else gcd(b, a % b)
