(** Permutation group operations.

    Permutations of {0, ..., n-1} represented as arrays.
    Used in Galois group identification.

    Includes Schreier-Sims algorithm for computing base and strong
    generating sets, enabling group order computation and membership
    testing. *)

type t = int array

let degree p = Array.length p

let identity n = Array.init n Fun.id

let compose a b =
  let n = Array.length a in
  Array.init n (fun i -> a.(b.(i)))

let inverse p =
  let n = Array.length p in
  let inv = Array.make n 0 in
  Array.iteri (fun i v -> inv.(v) <- i) p;
  inv

let apply p i = p.(i)

let is_identity p =
  let n = Array.length p in
  let rec go i =
    if i >= n then true
    else p.(i) = i && go (i + 1)
  in
  go 0

let order p =
  let id = identity (Array.length p) in
  let rec go current k =
    if current = id then k
    else go (compose p current) (k + 1)
  in
  go p 1

let equal a b = a = b

(** Cycle decomposition excluding fixed points.
    Each cycle starts from its smallest element. *)
let cycles p =
  let n = Array.length p in
  let visited = Array.make n false in
  let result = ref [] in
  for i = 0 to n - 1 do
    if not visited.(i) && p.(i) <> i then begin
      let cyc = ref [i] in
      visited.(i) <- true;
      let j = ref p.(i) in
      while !j <> i do
        cyc := !j :: !cyc;
        visited.(!j) <- true;
        j := p.(!j)
      done;
      result := List.rev !cyc :: !result
    end
  done;
  List.rev !result

(** Sign of a permutation: 1 for even, -1 for odd. *)
let sign p =
  let k = List.fold_left (fun acc c -> acc + List.length c - 1) 0 (cycles p) in
  if k mod 2 = 0 then 1 else -1

(** Build a permutation from cycle notation.
    Unlisted points are fixed. *)
let from_cycles n cycs =
  let p = Array.init n Fun.id in
  List.iter (fun cyc ->
    match cyc with
    | [] -> ()
    | _ ->
      let len = List.length cyc in
      List.iteri (fun i x ->
        let next = List.nth cyc ((i + 1) mod len) in
        p.(x) <- next) cyc
  ) cycs;
  p

(** Build a permutation from a full image list. *)
let from_mapping img =
  Array.of_list img

(** Orbit of a point under a group generated by the given permutations. *)
let orbit pt gens =
  let visited = Hashtbl.create 16 in
  let queue = Queue.create () in
  Hashtbl.add visited pt true;
  Queue.add pt queue;
  while not (Queue.is_empty queue) do
    let x = Queue.pop queue in
    List.iter (fun g ->
      let y = apply g x in
      if not (Hashtbl.mem visited y) then begin
        Hashtbl.add visited y true;
        Queue.add y queue
      end
    ) gens
  done;
  Hashtbl.fold (fun k _ acc -> k :: acc) visited [] |> List.sort Int.compare

(** {2 Schreier-Sims algorithm} *)

(** Base and strong generating set for a permutation group. *)
type bsgs = {
  base : int list;
  (** Transversals: for each base point, maps orbit points to
      coset representatives. *)
  transversals : (int, t) Hashtbl.t list;
  n : int;
}

(** Build a transversal by BFS from a base point using generators. *)
let build_transversal n pt gens =
  let trans = Hashtbl.create 16 in
  Hashtbl.add trans pt (identity n);
  let queue = Queue.create () in
  Queue.add pt queue;
  while not (Queue.is_empty queue) do
    let x = Queue.pop queue in
    let ux = Hashtbl.find trans x in
    List.iter (fun g ->
      let y = apply g x in
      if not (Hashtbl.mem trans y) then begin
        Hashtbl.add trans y (compose g ux);
        Queue.add y queue
      end
    ) gens
  done;
  trans

(** Sift a permutation through the BSGS, returning the residue. *)
let sift bsgs h =
  let rec go i h =
    if i >= List.length bsgs.base then h
    else
      let b = List.nth bsgs.base i in
      let img = apply h b in
      let trans = List.nth bsgs.transversals i in
      match Hashtbl.find_opt trans img with
      | None -> h
      | Some u -> go (i + 1) (compose (inverse u) h)
  in
  go 0 h

(** Extend the BSGS with a non-identity residue. *)
let extend_bsgs bsgs g =
  let n = bsgs.n in
  let fixed_levels =
    let rec count i =
      if i >= List.length bsgs.base then i
      else if apply g (List.nth bsgs.base i) = List.nth bsgs.base i then count (i + 1)
      else i
    in
    count 0
  in
  if fixed_levels >= List.length bsgs.base then begin
    (* g fixes all base points; add new level *)
    let pt = ref 0 in
    while apply g !pt = !pt do incr pt done;
    let trans = build_transversal n !pt [g] in
    { base = bsgs.base @ [!pt];
      transversals = bsgs.transversals @ [trans];
      n }
  end else begin
    (* Rebuild transversal at fixed_levels with g added *)
    let existing_reps =
      Hashtbl.fold (fun _ v acc -> v :: acc) (List.nth bsgs.transversals fixed_levels) []
    in
    let new_trans = build_transversal n (List.nth bsgs.base fixed_levels) (g :: existing_reps) in
    { base = bsgs.base;
      transversals =
        List.mapi (fun i t -> if i = fixed_levels then new_trans else t) bsgs.transversals;
      n }
  end

(** Compute Schreier generators at each level. *)
let schreier_gens bsgs gens =
  let result = ref [] in
  List.iteri (fun i trans ->
    let b = List.nth bsgs.base i in
    Hashtbl.iter (fun _ u ->
      let beta = apply u b in
      List.iter (fun s ->
        let s_beta = apply s beta in
        let u_s_beta =
          match Hashtbl.find_opt trans s_beta with
          | Some v -> v
          | None -> identity bsgs.n
        in
        let sg = compose (inverse u_s_beta) (compose s u) in
        if not (is_identity sg) then
          result := sg :: !result
      ) gens
    ) trans
  ) bsgs.transversals;
  !result

(** Compare two BSGS by base and transversal sizes. *)
let bsgs_equal a b =
  a.base = b.base &&
  List.length a.transversals = List.length b.transversals &&
  List.for_all2 (fun t1 t2 -> Hashtbl.length t1 = Hashtbl.length t2)
    a.transversals b.transversals

(** Build a BSGS from generators via incremental Schreier-Sims. *)
let schreier_sims n gens =
  let non_id = List.filter (fun g -> not (is_identity g)) gens in
  if non_id = [] then { base = []; transversals = []; n }
  else
    let sift_insert bsgs g =
      let r = sift bsgs g in
      if is_identity r then bsgs
      else extend_bsgs bsgs r
    in
    let initial = List.fold_left sift_insert { base = []; transversals = []; n } non_id in
    let rec saturate bsgs =
      let sg = schreier_gens bsgs gens in
      let bsgs' = List.fold_left sift_insert bsgs sg in
      if bsgs_equal bsgs' bsgs then bsgs'
      else saturate bsgs'
    in
    saturate initial

(** Group order from a BSGS. *)
let group_order bsgs =
  List.fold_left (fun acc t -> acc * Hashtbl.length t) 1 bsgs.transversals

(** Test membership in the group represented by a BSGS. *)
let group_contains bsgs g =
  is_identity (sift bsgs g)

(** Enumerate all elements of the group. *)
let group_elements bsgs =
  let n = bsgs.n in
  match bsgs.transversals with
  | [] -> [identity n]
  | _ ->
    let reps_list = List.map (fun t ->
      Hashtbl.fold (fun _ v acc -> v :: acc) t []
    ) bsgs.transversals in
    let rec cartesian = function
      | [] -> [[]]
      | xs :: rest ->
        let tails = cartesian rest in
        List.concat_map (fun x -> List.map (fun t -> x :: t) tails) xs
    in
    List.map (fun combo ->
      List.fold_left compose (identity n) combo
    ) (cartesian reps_list)

let to_string p =
  let n = Array.length p in
  let parts = List.init n (fun i -> string_of_int p.(i)) in
  "(" ^ String.concat " " parts ^ ")"
