-- |
-- Module      : Surd.Radical.Denest.Landau
-- Description : General denesting via Trager factoring over radical extension fields
-- Stability   : experimental
--
-- Implements Landau's denesting algorithm for nested radicals.
-- Given @nth-root(a)@ where @a@ is in a radical extension @K/Q@,
-- determines whether @nth-root(a)@ can be expressed using radicals of
-- lower nesting depth by factoring @x^n - a@ over @K@ using Trager's
-- algorithm.
--
-- === Algorithm
--
-- 1. Collect all radicals in the radicand @a@ and topologically sort them.
-- 2. Build a tower of field extensions @Q(alpha_1)(alpha_2)...@ where
--    each @alpha_i@ is a radical appearing in @a@.
-- 3. Evaluate @a@ in this extension field.
-- 4. Factor the polynomial @x^n - a@ over the extension field using
--    Trager's factoring algorithm ('factorSFOverExtension' or
--    'factorSFOverExtensionK' for nested extensions).
-- 5. If a factor of degree @d < n@ exists, extract the root from that
--    factor. For degree 1: direct extraction. For degree 2: quadratic
--    formula. For degree 3: Cardano's formula. For degree 4: Ferrari's
--    method.
--
-- === When denesting succeeds
--
-- Denesting succeeds when @x^n - a@ is reducible over the radical
-- extension field generated by the atoms in @a@. This happens precisely
-- when the Galois group of @x^n - a@ over @K@ is a proper subgroup of
-- the cyclic group @Z/nZ@, which occurs when certain roots of unity
-- or norm conditions are satisfied.
--
-- Currently supports radicands involving up to 4 distinct radicals
-- (building extension towers of depth 1-4).
module Surd.Radical.Denest.Landau
  ( -- * Top-level interface
    denestLandau,
    denestRadical,
  )
where

import Data.Complex (Complex (..))
import Math.Field.Extension
import Math.Polynomial.TragerFactoring (factorSFOverExtension, factorSFOverExtensionK)
import Math.Polynomial.Univariate
import Surd.Radical.Eval (evalComplexExact)
import Surd.Radical.Expr (collectRadicals, topoSortRadicals)
import Surd.Types

-- | Try to denest all radicals in an expression using Landau's algorithm.
--
-- Applies denesting recursively, bottom-up: inner radicals are denested
-- before outer ones. If denesting succeeds, the result is recursively
-- denested again.
denestLandau :: RadExpr Rational -> RadExpr Rational
denestLandau = go
  where
    go (Lit r) = Lit r
    go (Neg a) = Neg (go a)
    go (Add a b) = Add (go a) (go b)
    go (Mul a b) = Mul (go a) (go b)
    go (Inv a) = Inv (go a)
    go (Pow a n) = Pow (go a) n
    go (Root n a) =
      let a' = go a -- denest inner first
       in case denestRadical n a' of
            Just simplified -> go simplified -- recurse on result
            Nothing -> Root n a'

-- | Try to denest a specific radical: @nth-root(a)@.
--
-- Strategy:
--
-- 1. Try simple cases (perfect powers, known patterns)
-- 2. Collect radicals in @a@, build extension @K@ over @Q@
-- 3. Factor @x^n - a@ over @K@ using Trager's algorithm
-- 4. If a factor of degree @d < n@ exists, extract the simpler root
--
-- Returns @Just result@ if denesting succeeded, @Nothing@ if the
-- expression is irreducible (cannot be simplified).
--
-- Currently supports radicands with up to 4 distinct radical sub-expressions.
denestRadical :: Int -> RadExpr Rational -> Maybe (RadExpr Rational)
denestRadical n radicand =
  -- First try simple cases
  case trySimpleDenest n radicand of
    Just r -> Just r
    Nothing -> tryTragerDenest n radicand

-- | Simple denesting: rational radicands, perfect powers.
trySimpleDenest :: Int -> RadExpr Rational -> Maybe (RadExpr Rational)
trySimpleDenest _n (Lit _r) = Nothing -- handled by normalize already
trySimpleDenest 2 (Add (Lit _) (Mul (Lit _) (Root 2 (Lit _)))) =
  -- sqrt(a + b*sqrt c): classic Borodin denesting
  -- Already handled by Denest.Sqrt, skip here
  Nothing
trySimpleDenest _ _ = Nothing

-- | Try denesting via Trager factoring of x^n - a over the radical extension.
tryTragerDenest :: Int -> RadExpr Rational -> Maybe (RadExpr Rational)
tryTragerDenest n radicand =
  let radicals = collectRadicalsSimple radicand
   in case radicals of
        [] -> Nothing -- radicand is rational, nothing to denest
        [(deg, rad)] -> tryDenestDepth1 n radicand deg rad
        [(d1, r1), (d2, r2)] -> tryDenestDepth2 n radicand (d1, r1) (d2, r2)
        [(d1, r1), (d2, r2), (d3, r3)] ->
          tryDenestDepth3 n radicand (d1, r1) (d2, r2) (d3, r3)
        [(d1, r1), (d2, r2), (d3, r3), (d4, r4)] ->
          tryDenestDepth4 n radicand (d1, r1) (d2, r2) (d3, r3) (d4, r4)
        _ -> Nothing -- 5+ radicals not yet supported

-- | Denest nth-root(expr) where expr involves a single radical alpha = dth-root(r).
-- Builds K = Q(alpha) and factors x^n - a over K.
tryDenestDepth1 :: Int -> RadExpr Rational -> Int -> RadExpr Rational -> Maybe (RadExpr Rational)
tryDenestDepth1 n radicand deg rad =
  case evalRat rad of
    Nothing -> Nothing
    Just r ->
      let -- Build K = Q(alpha) where alpha^deg = r
          mp = mkPoly $ [-r] ++ replicate (deg - 1) 0 ++ [1]
          field = mkExtField mp "α"
          alpha = generator field
          -- Evaluate radicand in K
          aInK = evalInK field alpha (deg, rad) radicand
          -- Form x^n - a in K[x]
          xnMinusA = mkPoly $ [negate aInK] ++ replicate (n - 1) 0 ++ [embed field 1]
          -- Factor over K
          factors = factorSFOverExtension field xnMinusA
       in case [f | f <- factors, degree f > 0, degree f < n] of
            [] -> Nothing -- irreducible, no denesting possible
            (f : _) ->
              -- f is a factor of x^n - a of degree d < n
              -- The root of f is an expression involving alpha of lower radical degree
              extractRoot field alpha (deg, rad) f

-- | Extract a radical expression from a low-degree factor over K.
extractRoot ::
  ExtField Rational ->
  ExtElem Rational ->
  (Int, RadExpr Rational) ->
  Poly (ExtElem Rational) ->
  Maybe (RadExpr Rational)
extractRoot field alpha rad = extractRootGeneric toExpr
  where
    toExpr = extElemToRadExpr field alpha rad

-- | Generic root extraction from a polynomial factor of degree 1-4.
--
-- The @toExpr@ function converts field elements to radical expressions.
-- Handles:
--
-- * __Degree 1__: linear factor @x - c@ gives root @c@ directly.
-- * __Degree 2__: quadratic formula.
-- * __Degree 3__: Cardano's formula (handles casus irreducibilis via
--   complex cube roots of unity).
-- * __Degree 4__: Ferrari's method (resolvent cubic + quadratic extraction).
--
-- When multiple roots exist (degree >= 2), selects the one closest
-- to a real value (smallest imaginary part) via exact complex evaluation.
extractRootGeneric ::
  (Eq k, Fractional k) =>
  (k -> RadExpr Rational) ->
  Poly k ->
  Maybe (RadExpr Rational)
extractRootGeneric toExpr f
  | degree f == 1 =
      case unPoly f of
        [c, _] -> Just (toExpr (negate c))
        _ -> Nothing
  | degree f == 2 =
      case unPoly f of
        [c, b, _] ->
          let disc = b * b - 4 * c
              sqrtDisc = toExpr disc
              negB = toExpr (negate b)
              r1 = Mul (Inv (Lit 2)) (Add negB (Root 2 sqrtDisc))
              r2 = Mul (Inv (Lit 2)) (Add negB (Neg (Root 2 sqrtDisc)))
           in Just (pickClosestToReal [r1, r2])
        _ -> Nothing
  | degree f == 3 =
      -- Depressed cubic via Cardano
      case unPoly f of
        [d, c, b, _] ->
          -- x^3 + b*x^2 + c*x + d = 0 (monic)
          -- Depress: x = t - b/3
          let p = c - b * b / 3
              q = d - b * c / 3 + 2 * b * b * b / 27
              shift = Neg (toExpr (b / 3))
              halfQ = toExpr (q / 2)
              innerDisc = q * q / 4 + p * p * p / 27
              innerDiscE = toExpr innerDisc
              sqrtD = Root 2 innerDiscE
              u = Root 3 (Add (Neg halfQ) sqrtD)
              v = Root 3 (Add (Neg halfQ) (Neg sqrtD))
              -- Three roots via omega = (-1 + sqrt(-3))/2
              omega = Mul (Inv (Lit 2)) (Add (Lit (-1)) (Root 2 (Lit (-3))))
              omega2 = Mul (Inv (Lit 2)) (Add (Lit (-1)) (Neg (Root 2 (Lit (-3)))))
              root0 = Add (Add u v) shift
              root1 = Add (Add (Mul omega u) (Mul omega2 v)) shift
              root2 = Add (Add (Mul omega2 u) (Mul omega u)) shift
           in Just (pickClosestToReal [root0, root1, root2])
        _ -> Nothing
  | degree f == 4 =
      -- Quartic via Ferrari
      case unPoly f of
        [e, d, c, b, _] ->
          -- x^4 + b*x^3 + c*x^2 + d*x + e = 0 (monic)
          let p = c - 3 * b * b / 8
              q = d - b * c / 2 + b * b * b / 8
              r = e - b * d / 4 + b * b * c / 16 - 3 * b * b * b * b / 256
              bE = toExpr b
              shiftBack expr = Add expr (Neg (Mul (Inv (Lit 4)) bE))
           in if q == 0
                then -- Biquadratic
                  let disc = p * p - 4 * r
                      sqrtDisc = Root 2 (toExpr disc)
                      pE = toExpr p
                      t2_1 = Mul (Inv (Lit 2)) (Add (Neg pE) sqrtDisc)
                      t2_2 = Mul (Inv (Lit 2)) (Add (Neg pE) (Neg sqrtDisc))
                      roots =
                        [ shiftBack (Root 2 t2_1),
                          shiftBack (Neg (Root 2 t2_1)),
                          shiftBack (Root 2 t2_2),
                          shiftBack (Neg (Root 2 t2_2))
                        ]
                   in Just (pickClosestToReal roots)
                else -- General quartic: resolvent cubic y^3 - p*y^2 - 4*r*y + (4*p*r - q^2) = 0
                  let rcD = 4 * p * r - q * q
                      rcC = -4 * r
                      rcB = -p
                      -- Solve resolvent cubic (Poly k)
                      rcPoly = mkPoly [rcD, rcC, rcB, 1]
                   in case extractRootGeneric toExpr rcPoly of
                        Just yExpr ->
                          let sSquared = Add yExpr (Neg (toExpr p))
                              s = Root 2 sSquared
                              halfY = Mul (Inv (Lit 2)) yExpr
                              qOver2s = Mul (toExpr (q / 2)) (Inv s)
                              c1 = Add halfY (Neg qOver2s)
                              c2 = Add halfY qOver2s
                              disc1 = Add sSquared (Mul (Lit (-4)) c1)
                              disc2 = Add sSquared (Mul (Lit (-4)) c2)
                              sqD1 = Root 2 disc1
                              sqD2 = Root 2 disc2
                              t1 = Mul (Inv (Lit 2)) (Add (Neg s) sqD1)
                              t2 = Mul (Inv (Lit 2)) (Add (Neg s) (Neg sqD1))
                              t3 = Mul (Inv (Lit 2)) (Add s sqD2)
                              t4 = Mul (Inv (Lit 2)) (Add s (Neg sqD2))
                              roots = map shiftBack [t1, t2, t3, t4]
                           in Just (pickClosestToReal roots)
                        Nothing -> Nothing
        _ -> Nothing
  | otherwise = Nothing

-- | Pick the root expression closest to a real value (smallest imaginary part).
-- Uses exact complex evaluation to determine which candidate is most real.
pickClosestToReal :: [RadExpr Rational] -> RadExpr Rational
pickClosestToReal [] = error "pickClosestToReal: empty list"
pickClosestToReal [r] = r
pickClosestToReal roots =
  let scored = [(r, abs (imagPart (evalComplexExact r))) | r <- roots]
      imagPart (_ :+ y) = y
   in fst $ foldl1 (\a b -> if snd a <= snd b then a else b) scored

-- | Convert an ExtElem back to a RadExpr.
-- The element is a polynomial in alpha: elem = c_0 + c_1*alpha + c_2*alpha^2 + ...
extElemToRadExpr ::
  ExtField Rational ->
  ExtElem Rational ->
  (Int, RadExpr Rational) ->
  ExtElem Rational ->
  RadExpr Rational
extElemToRadExpr _ _ (deg, rad) (ExtElem (Poly cs) _) =
  let radical = Root deg rad
      -- elem = c_0 + c_1*alpha + c_2*alpha^2 + ...
      terms = [(c, i) | (i, c) <- zip [0 :: Int ..] cs, c /= 0]
   in case terms of
        [] -> Lit 0
        _ -> foldl1 Add [mkTerm c i radical | (c, i) <- terms]
  where
    mkTerm c 0 _ = Lit c
    mkTerm 1 1 a = a
    mkTerm c 1 a = Mul (Lit c) a
    mkTerm 1 i a = Pow a i
    mkTerm c i a = Mul (Lit c) (Pow a i)

-- | Collect distinct radicals from an expression, topologically sorted
-- so that radicals with rational radicands come first, followed by
-- radicals whose radicands depend only on earlier radicals.
collectRadicalsSimple :: RadExpr Rational -> [(Int, RadExpr Rational)]
collectRadicalsSimple = topoSortRadicals . collectRadicals

-- | Evaluate a RadExpr in Q(alpha).
evalInK ::
  ExtField Rational ->
  ExtElem Rational ->
  (Int, RadExpr Rational) ->
  RadExpr Rational ->
  ExtElem Rational
evalInK field alpha rad = go
  where
    go (Lit r) = embed field r
    go (Neg a) = negate (go a)
    go (Add a b) = go a + go b
    go (Mul a b) = go a * go b
    go (Inv a) = recip (go a)
    go (Root n a)
      | (n, a) == rad = alpha
      | otherwise = error "evalInK: unexpected radical"
    go (Pow a n)
      | n >= 0 = go a ^ n
      | otherwise = recip (go a ^ negate n)

-- | Denest nth-root(expr) where expr involves two radicals.
-- Builds a two-level extension Q(alpha_1)(alpha_2) and factors x^n - a over it.
tryDenestDepth2 ::
  Int ->
  RadExpr Rational ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  Maybe (RadExpr Rational)
tryDenestDepth2 n radicand rad1@(d1, r1) rad2@(d2, r2) =
  case (evalRat r1, evalRat r2) of
    (Just q1, Just q2) ->
      -- Both radicands are rational: build Q(alpha_1)(alpha_2)
      let -- Level 1: Q(alpha_1) where alpha_1^d1 = q1
          mp1 = mkPoly $ [-q1] ++ replicate (d1 - 1) 0 ++ [1]
          field1 = mkExtField mp1 "α₁"
          alpha1 = generator field1
          -- Evaluate r2 in Q(alpha_1) -- it's rational, so just embed
          q2InF1 = embed field1 q2
          -- Level 2: Q(alpha_1)(alpha_2) where alpha_2^d2 = q2
          mp2 = mkPoly $ [negate q2InF1] ++ replicate (d2 - 1) 0 ++ [embed field1 1]
          field2 = mkExtField mp2 "α₂"
          alpha2 = generator field2
          alpha1InF2 = embed field2 alpha1
          -- Evaluate radicand in Q(alpha_1)(alpha_2)
          aInK = evalInK2 field1 field2 alpha1InF2 alpha2 rad1 rad2 radicand
          -- Form x^n - a in Q(alpha_1)(alpha_2)[x]
          one2 = embed field2 (embed field1 1)
          xnMinusA = mkPoly $ [negate aInK] ++ replicate (n - 1) 0 ++ [one2]
          -- Factor over Q(alpha_1)(alpha_2) using generalized Trager.
          -- Base field factoring for K = Q(alpha_1) uses standard Trager.
          factorOverK = factorSFOverExtension field1
          factors = factorSFOverExtensionK factorOverK field2 xnMinusA
       in case [f | f <- factors, degree f > 0, degree f < n] of
            [] -> Nothing
            (f : _) -> extractRoot2 field1 field2 alpha1InF2 alpha2 rad1 rad2 f
    (Just q1, Nothing) ->
      -- r2 depends on alpha_1: build tower where alpha_1 comes first
      let mp1 = mkPoly $ [-q1] ++ replicate (d1 - 1) 0 ++ [1]
          field1 = mkExtField mp1 "α₁"
          alpha1 = generator field1
          -- Evaluate r2 in Q(alpha_1) -- r2 may involve alpha_1
          r2InF1 = evalInK field1 alpha1 rad1 r2
          mp2 = mkPoly $ [negate r2InF1] ++ replicate (d2 - 1) 0 ++ [embed field1 1]
          field2 = mkExtField mp2 "α₂"
          alpha2 = generator field2
          alpha1InF2 = embed field2 alpha1
          aInK = evalInK2 field1 field2 alpha1InF2 alpha2 rad1 rad2 radicand
          one2 = embed field2 (embed field1 1)
          xnMinusA = mkPoly $ [negate aInK] ++ replicate (n - 1) 0 ++ [one2]
          factorOverK = factorSFOverExtension field1
          factors = factorSFOverExtensionK factorOverK field2 xnMinusA
       in case [f | f <- factors, degree f > 0, degree f < n] of
            [] -> Nothing
            (f : _) -> extractRoot2 field1 field2 alpha1InF2 alpha2 rad1 rad2 f
    _ -> Nothing -- Can't handle if first radicand depends on second

-- | Extract a radical expression from a factor over Q(alpha_1)(alpha_2).
extractRoot2 ::
  ExtField Rational ->
  ExtField (ExtElem Rational) ->
  ExtElem (ExtElem Rational) -> -- alpha_1 lifted
  ExtElem (ExtElem Rational) -> -- alpha_2
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  Poly (ExtElem (ExtElem Rational)) ->
  Maybe (RadExpr Rational)
extractRoot2 field1 _field2 alpha1 alpha2 rad1 rad2 =
  extractRootGeneric toExpr
  where
    toExpr = extElemToRadExpr2 field1 alpha1 alpha2 rad1 rad2

-- | Convert an ExtElem (ExtElem Rational) back to a RadExpr.
-- elem = sum_i sum_j c_ij * alpha_1^i * alpha_2^j
extElemToRadExpr2 ::
  ExtField Rational ->
  ExtElem (ExtElem Rational) -> -- alpha_1 lifted
  ExtElem (ExtElem Rational) -> -- alpha_2
  (Int, RadExpr Rational) -> -- radical 1
  (Int, RadExpr Rational) -> -- radical 2
  ExtElem (ExtElem Rational) ->
  RadExpr Rational
extElemToRadExpr2 _field1 _alpha1 _alpha2 (d1, r1) (d2, r2) (ExtElem (Poly outerCs) _) =
  -- outerCs are coefficients of alpha_2: each is an ExtElem Rational (polynomial in alpha_1)
  let rad1Expr = Root d1 r1
      rad2Expr = Root d2 r2
      allTerms =
        concatMap
          ( \(j, ExtElem (Poly innerCs) _) ->
              [(c, i, j) | (i, c) <- zip [0 :: Int ..] innerCs, c /= 0]
          )
          (zip [0 :: Int ..] outerCs)
   in case allTerms of
        [] -> Lit 0
        _ -> foldl1 Add [mkTerm2 c i j rad1Expr rad2Expr | (c, i, j) <- allTerms]
  where
    mkTerm2 c 0 0 _ _ = Lit c
    mkTerm2 c i 0 a _ = mulCoeff c (powExpr a i)
    mkTerm2 c 0 j _ b = mulCoeff c (powExpr b j)
    mkTerm2 c i j a b = mulCoeff c (Mul (powExpr a i) (powExpr b j))

    mulCoeff 1 e = e
    mulCoeff c e = Mul (Lit c) e

    powExpr e 1 = e
    powExpr e k = Pow e k

-- | Evaluate a RadExpr in Q(alpha_1)(alpha_2) given two radicals.
evalInK2 ::
  ExtField Rational ->
  ExtField (ExtElem Rational) ->
  ExtElem (ExtElem Rational) -> -- alpha_1 lifted
  ExtElem (ExtElem Rational) -> -- alpha_2
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  RadExpr Rational ->
  ExtElem (ExtElem Rational)
evalInK2 field1 field2 alpha1 alpha2 rad1 rad2 = go
  where
    go (Lit r) = embed field2 (embed field1 r)
    go (Neg a) = negate (go a)
    go (Add a b) = go a + go b
    go (Mul a b) = go a * go b
    go (Inv a) = recip (go a)
    go (Root n a)
      | (n, a) == rad1 = alpha1
      | (n, a) == rad2 = alpha2
      | otherwise = error "evalInK2: unexpected radical"
    go (Pow a m)
      | m >= 0 = go a ^ m
      | otherwise = recip (go a ^ negate m)

-- | Denest nth-root(expr) where expr involves three radicals.
-- Builds a three-level extension Q(alpha_1)(alpha_2)(alpha_3) and factors x^n - a over it.
tryDenestDepth3 ::
  Int ->
  RadExpr Rational ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  Maybe (RadExpr Rational)
tryDenestDepth3 n radicand rad1@(d1, r1) rad2@(d2, r2) rad3@(d3, r3) =
  case evalRat r1 of
    Nothing -> Nothing -- after topo sort, first radicand should be rational
    Just q1 ->
      let -- Level 1: Q(alpha_1) where alpha_1^d1 = q1
          mp1 = mkPoly $ [-q1] ++ replicate (d1 - 1) 0 ++ [1]
          field1 = mkExtField mp1 "α₁"
          alpha1 = generator field1
          -- Level 2: Q(alpha_1)(alpha_2) where alpha_2^d2 = r2 evaluated in Q(alpha_1)
          r2InF1 = evalInK field1 alpha1 rad1 r2
          mp2 = mkPoly $ [negate r2InF1] ++ replicate (d2 - 1) 0 ++ [embed field1 1]
          field2 = mkExtField mp2 "α₂"
          alpha2 = generator field2
          alpha1InF2 = embed field2 alpha1
          -- Level 3: Q(alpha_1)(alpha_2)(alpha_3) where alpha_3^d3 = r3 evaluated in Q(alpha_1)(alpha_2)
          r3InF2 = evalInK2 field1 field2 alpha1InF2 alpha2 rad1 rad2 r3
          mp3 = mkPoly $ [negate r3InF2] ++ replicate (d3 - 1) 0 ++ [embed field2 (embed field1 1)]
          field3 = mkExtField mp3 "α₃"
          alpha3 = generator field3
          alpha1InF3 = embed field3 (embed field2 alpha1)
          alpha2InF3 = embed field3 alpha2
          -- Evaluate radicand in Q(alpha_1)(alpha_2)(alpha_3)
          aInK = evalInK3 field1 field2 field3 alpha1InF3 alpha2InF3 alpha3 rad1 rad2 rad3 radicand
          one3 = embed field3 (embed field2 (embed field1 1))
          xnMinusA = mkPoly $ [negate aInK] ++ replicate (n - 1) 0 ++ [one3]
          -- Factor over Q(alpha_1)(alpha_2)(alpha_3) using recursive Trager
          factorOverK1 = factorSFOverExtension field1
          factorOverK2 = factorSFOverExtensionK factorOverK1 field2
          factors = factorSFOverExtensionK factorOverK2 field3 xnMinusA
       in case [f | f <- factors, degree f > 0, degree f < n] of
            [] -> Nothing
            (f : _) ->
              extractRoot3
                field1
                field2
                field3
                alpha1InF3
                alpha2InF3
                alpha3
                rad1
                rad2
                rad3
                f

-- | Extract a radical expression from a factor over Q(alpha_1)(alpha_2)(alpha_3).
extractRoot3 ::
  ExtField Rational ->
  ExtField (ExtElem Rational) ->
  ExtField (ExtElem (ExtElem Rational)) ->
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_1 lifted
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_2 lifted
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_3
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  Poly (ExtElem (ExtElem (ExtElem Rational))) ->
  Maybe (RadExpr Rational)
extractRoot3 field1 _field2 _field3 alpha1 alpha2 alpha3 rad1 rad2 rad3 =
  extractRootGeneric toExpr
  where
    toExpr = extElemToRadExpr3 field1 alpha1 alpha2 alpha3 rad1 rad2 rad3

-- | Convert an ExtElem (ExtElem (ExtElem Rational)) back to a RadExpr.
extElemToRadExpr3 ::
  ExtField Rational ->
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_1 lifted
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_2 lifted
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_3
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  ExtElem (ExtElem (ExtElem Rational)) ->
  RadExpr Rational
extElemToRadExpr3 _field1 _alpha1 _alpha2 _alpha3 (d1, r1) (d2, r2) (d3, r3) (ExtElem (Poly outerCs) _) =
  let rad1Expr = Root d1 r1
      rad2Expr = Root d2 r2
      rad3Expr = Root d3 r3
      allTerms =
        concatMap
          ( \(k, ExtElem (Poly midCs) _) ->
              concatMap
                ( \(j, ExtElem (Poly innerCs) _) ->
                    [(c, i, j, k) | (i, c) <- zip [0 :: Int ..] innerCs, c /= 0]
                )
                (zip [0 :: Int ..] midCs)
          )
          (zip [0 :: Int ..] outerCs)
   in case allTerms of
        [] -> Lit 0
        _ -> foldl1 Add [mkTerm3 c i j k rad1Expr rad2Expr rad3Expr | (c, i, j, k) <- allTerms]
  where
    mkTerm3 c i j k a b d =
      let base = case (i, j, k) of
            (0, 0, 0) -> Nothing
            (_, 0, 0) -> Just (powExpr a i)
            (0, _, 0) -> Just (powExpr b j)
            (0, 0, _) -> Just (powExpr d k)
            (_, _, 0) -> Just (Mul (powExpr a i) (powExpr b j))
            (_, 0, _) -> Just (Mul (powExpr a i) (powExpr d k))
            (0, _, _) -> Just (Mul (powExpr b j) (powExpr d k))
            _ -> Just (Mul (Mul (powExpr a i) (powExpr b j)) (powExpr d k))
       in case base of
            Nothing -> Lit c
            Just e -> mulCoeff c e

    mulCoeff 1 e = e
    mulCoeff c e = Mul (Lit c) e

    powExpr e 1 = e
    powExpr e k = Pow e k

-- | Evaluate a RadExpr in Q(alpha_1)(alpha_2)(alpha_3) given three radicals.
evalInK3 ::
  ExtField Rational ->
  ExtField (ExtElem Rational) ->
  ExtField (ExtElem (ExtElem Rational)) ->
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_1 lifted
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_2 lifted
  ExtElem (ExtElem (ExtElem Rational)) -> -- alpha_3
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  RadExpr Rational ->
  ExtElem (ExtElem (ExtElem Rational))
evalInK3 field1 field2 field3 alpha1 alpha2 alpha3 rad1 rad2 rad3 = go
  where
    go (Lit r) = embed field3 (embed field2 (embed field1 r))
    go (Neg a) = negate (go a)
    go (Add a b) = go a + go b
    go (Mul a b) = go a * go b
    go (Inv a) = recip (go a)
    go (Root m a)
      | (m, a) == rad1 = alpha1
      | (m, a) == rad2 = alpha2
      | (m, a) == rad3 = alpha3
      | otherwise = error "evalInK3: unexpected radical"
    go (Pow a m)
      | m >= 0 = go a ^ m
      | otherwise = recip (go a ^ negate m)

-- | Denest nth-root(expr) where expr involves four radicals.
-- Builds a four-level extension Q(alpha_1)(alpha_2)(alpha_3)(alpha_4) and factors x^n - a over it.
tryDenestDepth4 ::
  Int ->
  RadExpr Rational ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  Maybe (RadExpr Rational)
tryDenestDepth4 n radicand rad1@(d1, r1) rad2@(d2, r2) rad3@(d3, r3) rad4@(d4, r4) =
  case evalRat r1 of
    Nothing -> Nothing -- after topo sort, first radicand should be rational
    Just q1 ->
      let -- Level 1: Q(alpha_1) where alpha_1^d1 = q1
          mp1 = mkPoly $ [-q1] ++ replicate (d1 - 1) 0 ++ [1]
          field1 = mkExtField mp1 "α₁"
          alpha1 = generator field1
          -- Level 2: Q(alpha_1)(alpha_2) where alpha_2^d2 = r2 evaluated in Q(alpha_1)
          r2InF1 = evalInK field1 alpha1 rad1 r2
          mp2 = mkPoly $ [negate r2InF1] ++ replicate (d2 - 1) 0 ++ [embed field1 1]
          field2 = mkExtField mp2 "α₂"
          alpha2 = generator field2
          alpha1InF2 = embed field2 alpha1
          -- Level 3: Q(alpha_1)(alpha_2)(alpha_3) where alpha_3^d3 = r3 evaluated in Q(alpha_1)(alpha_2)
          r3InF2 = evalInK2 field1 field2 alpha1InF2 alpha2 rad1 rad2 r3
          mp3 = mkPoly $ [negate r3InF2] ++ replicate (d3 - 1) 0 ++ [embed field2 (embed field1 1)]
          field3 = mkExtField mp3 "α₃"
          alpha3 = generator field3
          alpha1InF3 = embed field3 (embed field2 alpha1)
          alpha2InF3 = embed field3 alpha2
          -- Level 4: Q(alpha_1)(alpha_2)(alpha_3)(alpha_4) where alpha_4^d4 = r4 evaluated in Q(alpha_1)(alpha_2)(alpha_3)
          r4InF3 = evalInK3 field1 field2 field3 alpha1InF3 alpha2InF3 alpha3 rad1 rad2 rad3 r4
          mp4 = mkPoly $ [negate r4InF3] ++ replicate (d4 - 1) 0 ++ [embed field3 (embed field2 (embed field1 1))]
          field4 = mkExtField mp4 "α₄"
          alpha4 = generator field4
          alpha1InF4 = embed field4 (embed field3 (embed field2 alpha1))
          alpha2InF4 = embed field4 (embed field3 alpha2)
          alpha3InF4 = embed field4 alpha3
          -- Evaluate radicand in Q(alpha_1)(alpha_2)(alpha_3)(alpha_4)
          aInK =
            evalInK4
              field1
              field2
              field3
              field4
              alpha1InF4
              alpha2InF4
              alpha3InF4
              alpha4
              rad1
              rad2
              rad3
              rad4
              radicand
          one4 = embed field4 (embed field3 (embed field2 (embed field1 1)))
          xnMinusA = mkPoly $ [negate aInK] ++ replicate (n - 1) 0 ++ [one4]
          -- Factor over Q(alpha_1)(alpha_2)(alpha_3)(alpha_4) using recursive Trager
          factorOverK1 = factorSFOverExtension field1
          factorOverK2 = factorSFOverExtensionK factorOverK1 field2
          factorOverK3 = factorSFOverExtensionK factorOverK2 field3
          factors = factorSFOverExtensionK factorOverK3 field4 xnMinusA
       in case [f | f <- factors, degree f > 0, degree f < n] of
            [] -> Nothing
            (f : _) ->
              extractRoot4
                field1
                field2
                field3
                field4
                alpha1InF4
                alpha2InF4
                alpha3InF4
                alpha4
                rad1
                rad2
                rad3
                rad4
                f

-- | Extract a radical expression from a factor over Q(alpha_1)(alpha_2)(alpha_3)(alpha_4).
extractRoot4 ::
  ExtField Rational ->
  ExtField (ExtElem Rational) ->
  ExtField (ExtElem (ExtElem Rational)) ->
  ExtField (ExtElem (ExtElem (ExtElem Rational))) ->
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_1 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_2 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_3 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_4
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  Poly (ExtElem (ExtElem (ExtElem (ExtElem Rational)))) ->
  Maybe (RadExpr Rational)
extractRoot4 field1 _field2 _field3 _field4 alpha1 alpha2 alpha3 alpha4 rad1 rad2 rad3 rad4 =
  extractRootGeneric toExpr
  where
    toExpr = extElemToRadExpr4 field1 alpha1 alpha2 alpha3 alpha4 rad1 rad2 rad3 rad4

-- | Convert an ExtElem (ExtElem (ExtElem (ExtElem Rational))) back to a RadExpr.
extElemToRadExpr4 ::
  ExtField Rational ->
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_1 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_2 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_3 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_4
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) ->
  RadExpr Rational
extElemToRadExpr4
  _field1
  _alpha1
  _alpha2
  _alpha3
  _alpha4
  (d1, r1)
  (d2, r2)
  (d3, r3)
  (d4, r4)
  (ExtElem (Poly outerCs) _) =
    let rad1Expr = Root d1 r1
        rad2Expr = Root d2 r2
        rad3Expr = Root d3 r3
        rad4Expr = Root d4 r4
        allTerms =
          concatMap
            ( \(l, ExtElem (Poly mid2Cs) _) ->
                concatMap
                  ( \(k, ExtElem (Poly mid1Cs) _) ->
                      concatMap
                        ( \(j, ExtElem (Poly innerCs) _) ->
                            [(c, i, j, k, l) | (i, c) <- zip [0 :: Int ..] innerCs, c /= 0]
                        )
                        (zip [0 :: Int ..] mid1Cs)
                  )
                  (zip [0 :: Int ..] mid2Cs)
            )
            (zip [0 :: Int ..] outerCs)
     in case allTerms of
          [] -> Lit 0
          _ ->
            foldl1
              Add
              [ mkTerm4 c i j k l rad1Expr rad2Expr rad3Expr rad4Expr
                | (c, i, j, k, l) <- allTerms
              ]
    where
      mkTerm4 c i j k l a b d e =
        let factors =
              [powExpr a i | i /= 0]
                ++ [powExpr b j | j /= 0]
                ++ [powExpr d k | k /= 0]
                ++ [powExpr e l | l /= 0]
            base = case factors of
              [] -> Nothing
              [x] -> Just x
              (x : xs) -> Just (foldl Mul x xs)
         in case base of
              Nothing -> Lit c
              Just expr -> mulCoeff c expr

      mulCoeff 1 expr = expr
      mulCoeff c expr = Mul (Lit c) expr

      powExpr expr 1 = expr
      powExpr expr p = Pow expr p

-- | Evaluate a RadExpr in Q(alpha_1)(alpha_2)(alpha_3)(alpha_4) given four radicals.
evalInK4 ::
  ExtField Rational ->
  ExtField (ExtElem Rational) ->
  ExtField (ExtElem (ExtElem Rational)) ->
  ExtField (ExtElem (ExtElem (ExtElem Rational))) ->
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_1 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_2 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_3 lifted
  ExtElem (ExtElem (ExtElem (ExtElem Rational))) -> -- alpha_4
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  (Int, RadExpr Rational) ->
  RadExpr Rational ->
  ExtElem (ExtElem (ExtElem (ExtElem Rational)))
evalInK4 field1 field2 field3 field4 alpha1 alpha2 alpha3 alpha4 rad1 rad2 rad3 rad4 = go
  where
    go (Lit r) = embed field4 (embed field3 (embed field2 (embed field1 r)))
    go (Neg a) = negate (go a)
    go (Add a b) = go a + go b
    go (Mul a b) = go a * go b
    go (Inv a) = recip (go a)
    go (Root m a)
      | (m, a) == rad1 = alpha1
      | (m, a) == rad2 = alpha2
      | (m, a) == rad3 = alpha3
      | (m, a) == rad4 = alpha4
      | otherwise = error "evalInK4: unexpected radical"
    go (Pow a m)
      | m >= 0 = go a ^ m
      | otherwise = recip (go a ^ negate m)

-- | Try to evaluate a RadExpr as a rational (no radicals).
evalRat :: RadExpr Rational -> Maybe Rational
evalRat (Lit r) = Just r
evalRat (Neg a) = negate <$> evalRat a
evalRat (Add a b) = (+) <$> evalRat a <*> evalRat b
evalRat (Mul a b) = (*) <$> evalRat a <*> evalRat b
evalRat (Inv a) = recip <$> evalRat a
evalRat (Pow a n) = (^^ n) <$> evalRat a
evalRat (Root _ _) = Nothing
