package demo

import surd.*
import surd.Trig.*

/** Generate tables of exact trigonometric values.
  *
  * Computes cos(k*pi/n) and sin(k*pi/n) for specified denominators,
  * displaying the results as radical expressions in text or LaTeX format.
  */
object TrigTableDemo:

  def main(args: Array[String]): Unit =
    val denoms = if args.isEmpty then Vector(4, 6, 8, 12) else args.map(_.toInt).toVector
    val format = if args.contains("--latex") then "latex" else "text"

    if format == "latex" then
      printLatexTable(denoms)
    else
      printTextTable(denoms)

  /** Print a text table of exact trig values. */
  private def printTextTable(denoms: Vector[Int]): Unit =
    println("Exact Trigonometric Values")
    println("=" * 80)
    println()

    for n <- denoms do
      println(s"--- Denominator $n ---")
      println(f"${"angle"}%-12s | ${"cos"}%-40s | ${"sin"}%-40s")
      println("-" * 95)

      for k <- 0 to n do
        val angle = if k == 0 then "0"
        else if k == n then s"${k}pi/$n"
        else s"${k}pi/$n"

        val cosResult = simplifyTrigResult(cosExact(k.toLong, n.toLong))
        val sinResult = simplifyTrigResult(sinExact(k.toLong, n.toLong))

        val cosStr = renderText(cosResult)
        val sinStr = renderText(sinResult)

        println(f"$angle%-12s | $cosStr%-40s | $sinStr%-40s")

      println()

  /** Print a LaTeX table of exact trig values. */
  private def printLatexTable(denoms: Vector[Int]): Unit =
    println("""\documentclass[11pt]{article}""")
    println("""\usepackage[a4paper,margin=1in]{geometry}""")
    println("""\usepackage{amsmath,amssymb}""")
    println("""\usepackage{longtable}""")
    println("""\usepackage{booktabs}""")
    println("""\title{Exact Trigonometric Values}""")
    println("""\author{Generated by surd (Scala 3)}""")
    println("""\date{}""")
    println("""\begin{document}""")
    println("""\maketitle""")
    println()

    for n <- denoms do
      println(s"\\section*{Denominator $n}")
      println("""\begin{longtable}{cll}""")
      println("""\toprule""")
      println("""$\theta$ & $\cos\theta$ & $\sin\theta$ \\""")
      println("""\midrule""")
      println("""\endhead""")

      for k <- 0 to n do
        val angle = latexAngle(k, n)
        val cosResult = simplifyTrigResult(cosExact(k.toLong, n.toLong))
        val sinResult = simplifyTrigResult(sinExact(k.toLong, n.toLong))

        val cosStr = renderLatex(cosResult)
        val sinStr = renderLatex(sinResult)

        println(s"$$$angle$$ & $$$cosStr$$ & $$$sinStr$$ \\\\")

      println("""\bottomrule""")
      println("""\end{longtable}""")
      println()

    println("""\end{document}""")

  /** Render a TrigResult as text. */
  private def renderText(tr: TrigResult): String = tr match
    case TrigResult.Radical(expr) => Pretty.pretty(expr)
    case TrigResult.MinPoly(poly) => s"minpoly: $poly"

  /** Render a TrigResult as LaTeX. */
  private def renderLatex(tr: TrigResult): String = tr match
    case TrigResult.Radical(expr) => LaTeX.latex(expr)
    case TrigResult.MinPoly(poly) => s"\\text{minpoly: }$poly"

  /** Format an angle k*pi/n as LaTeX. */
  private def latexAngle(k: Int, n: Int): String =
    if k == 0 then "0"
    else if k == n then "\\pi"
    else if k == 1 then s"\\frac{\\pi}{$n}"
    else s"\\frac{${k}\\pi}{$n}"
